### ISSUE TITLE
I can not get the original Bastrop dataset now. Would you please share a new link with me?

### ISSUE THREAD

**Issue by Sherlock-sen** [DavidJimenezS/GBF-CD#3]
I would really appreciate your help.

**Comment by DavidJimenezS** [comment]
Dear Sherlock-sens,

Thank you for letting me know about this issue. Seems that the owner of the dataset deletes his site at google.
Nonetheless, I still have the original dataset. So, I've just updated the link.

Now you should be able to download it.  Do not hesitate in letting me know if anything happens.

Best 
David

**Comment by Sherlock-sen** [comment]
Dear David,
I am very grateful for your help!!!!
Best
Sen

**Comment by DavidJimenezS** [comment]
My pleasure,

Hope the best for your research work.

Best
David
